server:
  error:
    include-message: on_param

spring:
  datasource:
    url: jdbc:postgresql://ec2-54-84-238-74.compute-1.amazonaws.com:5432/d477lbn7e6ridh
    username: reixjwfoloviqd
    password: 9f34a3c11f8db21bf33024d9e23e2766c7d16111bc19e1397437f89fac285ee9
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: debug


#Produção
#spring.datasource.url=${JDBC_DATASOURCE_URL}
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true

#Desenvolvimento
#spring.datasource.url= jdbc:postgresql://ec2-54-84-238-74.compute-1.amazonaws.com:5432/d477lbn7e6ridh
#spring.datasource.username=reixjwfoloviqd
#spring.datasource.password=9f34a3c11f8db21bf33024d9e23e2766c7d16111bc19e1397437f89fac285ee9
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true


